language: shell

services:
  - docker

before_install:
  - docker pull archimg/base
  - docker run -itd --name arch_linux archimg/base

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'
  - docker exec arch_linux bash -c "pacman --version"
